export const FONT_FAMILIES: Array<{ label: string; value: string }> = [
  { label: 'Poppins (Sans)', value: 'Poppins' },
  { label: 'Roboto (Sans)', value: 'Roboto' },
  { label: 'Lato (Sans)', value: 'Lato' },
  { label: 'Open Sans (Sans)', value: 'Open Sans' },
  { label: 'Montserrat (Sans)', value: 'Montserrat' },
  { label: 'Work Sans (Sans)', value: 'Work Sans' },
  { label: 'Fira Sans (Sans)', value: 'Fira Sans' },
  { label: 'DM Sans (Sans)', value: 'DM Sans' },
  { label: 'Manrope (Sans)', value: 'Manrope' },
  { label: 'Raleway (Sans)', value: 'Raleway' },
  { label: 'Ubuntu (Sans)', value: 'Ubuntu' },
  { label: 'Oswald (Sans)', value: 'Oswald' },
  { label: 'Helvetica (Sans Serif)', value: 'Helvetica' },
  { label: 'Arial (Sans Serif)', value: 'Arial' },
  { label: 'Verdana (Sans Serif)', value: 'Verdana' },
  { label: 'Tahoma (Sans Serif)', value: 'Tahoma' },
  { label: 'Trebuchet MS (Sans Serif)', value: 'Trebuchet MS' },
  { label: 'Georgia (Serif)', value: 'Georgia' },
  { label: 'Times New Roman (Serif)', value: 'Times New Roman' },
  { label: 'Garamond (Serif)', value: 'Garamond' },
  { label: 'Palatino (Serif)', value: 'Palatino' },
  { label: 'Merriweather (Serif)', value: 'Merriweather' },
  { label: 'Playfair Display (Serif)', value: 'Playfair Display' },
  { label: 'PT Serif (Serif)', value: 'PT Serif' },
  { label: 'Baskerville (Serif)', value: 'Baskerville' },
  { label: 'Cambria (Serif)', value: 'Cambria' },
  { label: 'Courier New (Monospace)', value: 'Courier New' },
  { label: 'Source Code Pro (Monospace)', value: 'Source Code Pro' },
  { label: 'Dancing Script (Cursive)', value: 'Dancing Script' },
  { label: 'Pacifico (Cursive)', value: 'Pacifico' },
  { label: 'Great Vibes (Calligraphy)', value: 'Great Vibes' },
  { label: 'Sacramento (Calligraphy)', value: 'Sacramento' },
];
